### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by mkusaka** [mikeshimura/goreport#11]
Currently, there does not appear to be a license for this module.

Is it possible to clarify the license?

The following may be helpful in adding a license

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

I would be happy with an MIT license :)

**Comment by mikeshimura** [comment]
MIT Licence added.
Thnak you

**Comment by mkusaka** [comment]
@mikeshimura Thanks!
